### ISSUE TITLE
What does "do not reimplement chaining" mean?

### ISSUE THREAD

**Issue by georgek** [sobolevn/flake8-broken-line#111]
The first two examples are good because they provide reasonable alternatives to using the line break. But the third, I'm not sure what it means. How is the programming "implementing" chaining? Can we just suggest a Pythonic alternative instead?

**Comment by sobolevn** [comment]
Oh, thanks for this question! 

I use several other languages and they all have some kind of chaining (or piping).

Like, `js` has:

```js
some
   .first()
   .second()
   .finalize()
```

And `elixir` has:

```elixir
some
|> first()
|> second()
|> finalize()
```

But, python is not suited for this kind of chaining. Instead I use this indentation:

```python
some.first(
   param1, param2,
).second(
   keyword=value,
).finalize()
```

It allows me not to use `\` to break lines. On the other hand when I have calls without any params: I ask myself if design is good enough. Because it looks and feels unpythonic. 

I hope this illustrates my idea well enough! 👍

**Comment by georgek** [comment]
Thanks, this makes sense. I think the wording is just odd. Maybe instead of "do not reimplement chaining" it should just be "do not use for method chaining" and provide the alternative formatting you've given here.

**Comment by sobolevn** [comment]
I agree, this will be way more clear. Do you want to send a PR?
